---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/attendances":
    get:
      summary: list attendances
      responses:
        '200':
          description: successful
    post:
      summary: create attendance
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: date
                present:
                  type: boolean
                user_id:
                  type: bigint
              required:
              - date
              - present
              - user_id
  "/attendances/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show attendance
      responses:
        '200':
          description: successful
    patch:
      summary: update attendance
      responses:
        '200':
          description: successful
    put:
      summary: update attendance
      responses:
        '200':
          description: successful
    delete:
      summary: delete attendance
      responses:
        '200':
          description: successful
  "/user/attendance":
    get:
      summary: personal_attendance attendance
      responses:
        '200':
          description: successful
  "/chats":
    get:
      summary: list chats
      responses:
        '200':
          description: successful
    post:
      summary: create chat
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: text
                user_id:
                  type: bigint
                unit_id:
                  type: bigint
              required:
              - message
              - user_id
              - unit_id
  "/chats/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show chat
      responses:
        '200':
          description: successful
    patch:
      summary: update chat
      responses:
        '200':
          description: successful
    put:
      summary: update chat
      responses:
        '200':
          description: successful
    delete:
      summary: delete chat
      responses:
        '200':
          description: successful
  "/courses":
    get:
      summary: list courses
      responses:
        '200':
          description: successful
    post:
      summary: create course
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                lesson:
                  type: string
              required:
              - name
              - lesson
  "/courses/new":
    get:
      summary: new course
      responses:
        '200':
          description: successful
  "/courses/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit course
      responses:
        '200':
          description: successful
  "/courses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show course
      responses:
        '200':
          description: successful
    patch:
      summary: update course
      responses:
        '200':
          description: successful
    put:
      summary: update course
      responses:
        '200':
          description: successful
    delete:
      summary: delete course
      responses:
        '200':
          description: successful
  "/exams":
    get:
      summary: list exams
      responses:
        '200':
          description: successful
    post:
      summary: create exam
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                unit_id:
                  type: bigint
                user_id:
                  type: bigint
                duration:
                  type: integer
              required:
              - unit_id
              - user_id
              - duration
  "/exams/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show exam
      responses:
        '200':
          description: successful
    patch:
      summary: update exam
      responses:
        '200':
          description: successful
    put:
      summary: update exam
      responses:
        '200':
          description: successful
    delete:
      summary: delete exam
      responses:
        '200':
          description: successful
  "/libraries":
    get:
      summary: list libraries
      responses:
        '200':
          description: successful
    post:
      summary: create library
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: bigint
                resource_id:
                  type: bigint
              required:
              - user_id
              - resource_id
  "/libraries/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show library
      responses:
        '200':
          description: successful
    patch:
      summary: update library
      responses:
        '200':
          description: successful
    put:
      summary: update library
      responses:
        '200':
          description: successful
    delete:
      summary: delete library
      responses:
        '200':
          description: successful
  "/messages":
    get:
      summary: list messages
      responses:
        '200':
          description: successful
    post:
      summary: create message
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: text
                user_id:
                  type: bigint
                unit_id:
                  type: bigint
              required:
              - content
              - user_id
              - unit_id
  "/messages/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show message
      responses:
        '200':
          description: successful
    patch:
      summary: update message
      responses:
        '200':
          description: successful
    put:
      summary: update message
      responses:
        '200':
          description: successful
    delete:
      summary: delete message
      responses:
        '200':
          description: successful
  "/resources":
    get:
      summary: list resources
      responses:
        '200':
          description: successful
    post:
      summary: create resource
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                file_url:
                  type: string
                unit_id:
                  type: bigint
              required:
              - name
              - file_url
              - unit_id
  "/resources/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show resource
      responses:
        '200':
          description: successful
    patch:
      summary: update resource
      responses:
        '200':
          description: successful
    put:
      summary: update resource
      responses:
        '200':
          description: successful
    delete:
      summary: delete resource
      responses:
        '200':
          description: successful
  "/schools":
    get:
      summary: list schools
      responses:
        '200':
          description: successful
    post:
      summary: create school
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
                contact_details:
                  type: integer
              required:
              - name
              - address
              - contact_details
  "/schools/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show school
      responses:
        '200':
          description: successful
    patch:
      summary: update school
      responses:
        '200':
          description: successful
    put:
      summary: update school
      responses:
        '200':
          description: successful
    delete:
      summary: delete school
      responses:
        '200':
          description: successful
  "/units":
    get:
      summary: list units
      responses:
        '200':
          description: successful
    post:
      summary: create unit
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                school_id:
                  type: bigint
                user_id:
                  type: bigint
              required:
              - name
              - school_id
              - user_id
  "/units/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show unit
      responses:
        '200':
          description: successful
    patch:
      summary: update unit
      responses:
        '200':
          description: successful
    put:
      summary: update unit
      responses:
        '200':
          description: successful
    delete:
      summary: delete unit
      responses:
        '200':
          description: successful
  "/user_courses":
    get:
      summary: list user_courses
      responses:
        '200':
          description: successful
    post:
      summary: create user_course
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: bigint
                unit_id:
                  type: bigint
              required:
              - user_id
              - unit_id
  "/user_courses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user_course
      responses:
        '200':
          description: successful
    patch:
      summary: update user_course
      responses:
        '200':
          description: successful
    put:
      summary: update user_course
      responses:
        '200':
          description: successful
    delete:
      summary: delete user_course
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: integer
                course:
                  type: string
                gender:
                  type: string
                school_id:
                  type: bigint
              required:
              - username
              - email
              - password
              - role
              - course
              - gender
              - school_id
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
  "/video_conferences":
    get:
      summary: list video_conferences
      responses:
        '200':
          description: successful
    post:
      summary: create video_conference
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: bigint
                unit_id:
                  type: bigint
                meeting_name:
                  type: string
                meeting_url:
                  type: string
              required:
              - user_id
              - unit_id
              - meeting_name
              - meeting_url
  "/video_conferences/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show video_conference
      responses:
        '200':
          description: successful
    patch:
      summary: update video_conference
      responses:
        '200':
          description: successful
    put:
      summary: update video_conference
      responses:
        '200':
          description: successful
    delete:
      summary: delete video_conference
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
