source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.4"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4", ">= 7.0.4.3"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.4.5"

gem 'active_model_serializers'

gem 'bcrypt'

gem 'faker'

# gem 'rswag'

# gem 'rspec-rails'

# gem 'rswag-ui'

gem 'actionmailer', '~> 7.0', '>= 7.0.4.3'

# gem 'cancancan'

gem 'rack-cors'

gem 'actioncable'

# gem 'action_cable_client', '~> 3.1'


# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'rspec', '~> 3.12'
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  # gem 'sqlite3'
  gem 'rspec-rails', '~>5.0.0'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  gem 'rspec-json_expectations'
  gem 'shoulda-matchers', '~> 4.0'
end


gem 'cancancan', '~> 3.5'

gem 'factory_bot_rails', '~> 6.2'

# gem 'devise', '~> 4.9', '>= 4.9.2'